# This workflow will build and test the C++Sparse library and the associated
# Python package. It relies on the makefile to call CMake for building the C++
# code and the pybind11 package.
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # continue testing other OSes even if one fails
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Compiler (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get update
          sudo apt-get install -y clang-21 libc++-21-dev libc++abi-21-dev
          echo "CC=clang-21" >> $GITHUB_ENV
          echo "CXX=clang++-21" >> $GITHUB_ENV
          echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV
          echo "LDFLAGS=--stdlib=libc++ -lc++abi -L/usr/lib/llvm-21/lib" >> $GITHUB_ENV
          which clang++
          which clang++-21
          clang++ --version
          clang++-21 --version

      - name: Install Compiler (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install llvm@21
          LLVM_PREFIX=$(brew --prefix llvm@21)
          echo "CC=${LLVM_PREFIX}/bin/clang" >> $GITHUB_ENV
          echo "CXX=${LLVM_PREFIX}/bin/clang++" >> $GITHUB_ENV
          echo "LDFLAGS=-L${LLVM_PREFIX}/lib/c++ -Wl,-rpath,$LLVM_PREFIX/lib/c++" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pybind11
        run: |
          pip install --upgrade pip
          pip install pybind11

      - name: Build C++ Code
        run: make tests

      - name: Run C++ unit tests
        run: ./test_csparse

      - name: Build and Install Python C++ module
        run: |
          make python
          pip install -e "${{ github.workspace }}/python[dev]"
          ls -l python/csparse

      - name: Run Python unit tests with conditional reruns
        run: ./run_pytest.sh -v

      - name: Run Python unit tests with figures
        env:
          MPLBACKEND: agg  # use headless backend for matplotlib
        run: ./run_pytest.sh --make-figures

      - name: Upload Test Figures
        uses: actions/upload-artifact@v4
        with:
          # Use a unique name for each OS and Python version
          name: test-figures-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./test_figures/
          if-no-files-found: error

      - name: Build and Run C++ Demos
        run: |
          make run_demos
