# This workflow will build and test the C++Sparse library and the associated
# Python package. It relies on the makefile to call CMake for building the C++
# code and the pybind11 package.
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # continue testing other OSes even if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install pybind11
        run: |
          python -m pip install --upgrade pip
          pip install pybind11

      - name: Configure CMake
        run: |
          mkdir -p build
          cmake -S . -B build \
            -DCMAKE_PREFIX_PATH="$(python -m pybind11 --cmakedir)"

      # Build and test C++
      - name: Build and Test C++ Code
        run: |
          cmake --build build --target test_csparse
          ./test_csparse

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install Python dependencies and development tools
      - name: Install Python dependencies
        run: |
          cd python
          pip install --upgrade pip
          pip install -e ".[dev]"

      # Run Python unit tests
      - name: Run Python tests
        # TODO pytest --make-figures
        # env:
        #   MPLBACKEND: agg  # use headless backend for matplotlib
        run: |
          pwd
          cd ../
          tree -L 2
          cmake --build build --target csparse
          cmake --install build
          pytest
